### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by machawk1** [irontonbrewing/tilt_perl#1]
I was considering adapting your code for my own use on macOS but noticed that there is no license file in this repo. Would you mind adding one so we can be clear on what is permitted for reuse (e.g., MIT, GPL)?

**Comment by irontonbrewing** [comment]
Hi Mat,

Yes, sorry I forgot a license. This is actually my first public github
project, so I'm a little new to these things. A standard MIT license has
been pushed.

I'm curious, what do you plan to adapt this for? Are you also a homebrewer?

Cheers!
-John

**Comment by machawk1** [comment]
@irontonbrewing Really just to get familiar with the data format the TILT is sending over Bluetooth beyond what's going on behind the scenes on the ISO. I've an RPi [talking to a TILT now](https://share.brewfather.app/ddjz0iGZZ6f7CB) but am capable of DIYing more functionality, though I haven't touched Perl in a decade+.

> Are you also a homebrewer?

👍

**Comment by irontonbrewing** [comment]
Yeah perl/Tk is very old but perl 5 is still maintained and updated. I use
perl/Tk every day at work so I’m most comfortable with it.

**Comment by machawk1** [comment]
@irontonbrewing No complaints here — use the tools that you know and that work well for you. 🍻
